apiVersion: v1
kind: Service
metadata:
  name: wxwork-webhook
spec:
  selector:
    app: wxwork-webhook
  ports:
    - name: test-webhook
      protocol: TCP
      port: 5233
      targetPort: 5233
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wxwork-webhook
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wxwork-webhook
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wxwork-webhook
    spec:
      automountServiceAccountToken: false
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - wxwork-webhook
            weight: 100
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      dnsPolicy: ClusterFirst
      initContainers:
      - name: wait-internet
        image: busybox:1.26
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
        command:
        - "/bin/sh"
        - "-c"
        - "until nc -zv www.baidu.com 80 -w1; do echo 'waiting for access Internet'; sleep 1; done"
      containers:
      - name: wxwork-webhook1
        image: luanlengli/wxwork-webhook:v0.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 20Mi
        ports:
        - containerPort: 5233
        workingDir: /usr/local/wxwork-webhook/
        command:
        - "python"
        - "app.py"
        - "--wxwork-webhook"
        - "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxx"
        - "--port"
        - "5233"
        volumeMounts:
        - name: timezone-volume
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: timezone-volume
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai